sudo: required
services:
  - docker

before_install:
  - docker build -t lejeunen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lejeunen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "nle"
  env: "docker-react-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-840205991060"
  bucket_path: "nle"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"